create table employee (
  id bigint generated by default as identity (start with 1),
  first_name varchar(255),
  last_name varchar(255),
  designation varchar(255),
  email varchar(255),
  phone varchar(255),
  photo varchar(255),
  primary key (id)
);

create table login(
	id bigint generated by default as identity(start with 1),
	user_name varchar(255),
	password varchar(255),
	role varchar(32),
	enabled boolean,
	primary key (id)
);