create table consultant (
  id bigint generated by default as identity (start with 1),
  first_name varchar(255),
  last_name varchar(255),
  designation varchar(255),
  email varchar(255),
  phone varchar(255),
  photo varchar(255),
  quote varchar(255),
  primary key (id)
);