create table employee (
  id bigint generated by default as identity (start with 1000),
  first_name varchar(255) not null,
  last_name varchar(255) not null,
  photo varchar(255) not null,
  email varchar(255) not null,
  phone varchar(255),
  location varchar(255),
  designation varchar(255),
  gender varchar(6),
  birth_date date,
  joining_date date,
  marriage_date date,
  role varchar(255) not null,
  enabled bit not null,
  primary key (id)
);

create table login(
	id bigint generated by default as identity(start with 100000),
	user_name varchar(255)  not null,
	password varchar(255) not null,
	primary key (id)
);
